"""Add sub to user

Revision ID: 6c3c302f364b
Revises: 
Create Date: 2025-05-06 11:03:49.842287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3c302f364b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_sub')
        batch_op.create_index(batch_op.f('ix_user_sub'), ['sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sub'))
        batch_op.create_index('idx_user_sub', ['sub'], unique=1)

    # ### end Alembic commands ###
