"""removed day of week to db

Revision ID: 877472cd27b7
Revises: 12a7c9c8d790
Create Date: 2025-05-28 09:21:48.752555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877472cd27b7'
down_revision = '12a7c9c8d790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
