"""Remove Post, Message, Notification and add fitness models

Revision ID: a787dc4cc7a4
Revises: 
Create Date: 2025-05-10 12:17:12.105713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a787dc4cc7a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('force', sa.Enum('STATIC', 'PULL', 'PUSH', name='force'), nullable=True),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='experiencelevel'), nullable=False),
    sa.Column('mechanic', sa.Enum('ISOLATION', 'COMPOUND', name='mechanic'), nullable=True),
    sa.Column('equipment', sa.Enum('MEDICINE_BALL', 'DUMBBELL', 'BODY_ONLY', 'BANDS', 'KETTLEBELLS', 'FOAM_ROLL', 'CABLE', 'MACHINE', 'BARBELL', 'EXERCISE_BALL', 'E_Z_CURL_BAR', 'OTHER', name='equipment'), nullable=True),
    sa.Column('category', sa.Enum('POWERLIFTING', 'STRENGTH', 'STRETCHING', 'CARDIO', 'OLYMPIC_WEIGHTLIFTING', 'STRONGMAN', 'PLYOMETRICS', name='category'), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_equipment'), ['equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_name'), ['name'], unique=False)

    op.create_table('exercise_muscle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muscle', sa.Enum('ABDOMINALS', 'ABDUCTORS', 'ADDUCTORS', 'BICEPS', 'CALVES', 'CHEST', 'FOREARMS', 'GLUTES', 'HAMSTRINGS', 'LATS', 'LOWER_BACK', 'MIDDLE_BACK', 'NECK', 'QUADRICEPS', 'SHOULDERS', 'TRAPS', 'TRICEPS', name='muscle'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('sub', sa.String(length=128), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('fitness_goal', sa.String(length=64), nullable=True),
    sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='experiencelevel'), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('weekly_workouts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('exercise_muscle_association',
    sa.Column('exercise_id', sa.String(length=50), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_id'], ['exercise_muscle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )
    op.create_table('workout_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_plan_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=50), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_log_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_log_workout_plan_id'), ['workout_plan_id'], unique=False)

    op.create_table('workout_plan_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_plan_exercise_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_plan_exercise_workout_plan_id'), ['workout_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_plan_exercise_workout_plan_id'))
        batch_op.drop_index(batch_op.f('ix_workout_plan_exercise_exercise_id'))

    op.drop_table('workout_plan_exercise')
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_log_workout_plan_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_log_exercise_id'))

    op.drop_table('exercise_log')
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_plan_user_id'))

    op.drop_table('workout_plan')
    op.drop_table('exercise_muscle_association')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('exercise_muscle')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_name'))
        batch_op.drop_index(batch_op.f('ix_exercise_level'))
        batch_op.drop_index(batch_op.f('ix_exercise_equipment'))
        batch_op.drop_index(batch_op.f('ix_exercise_category'))

    op.drop_table('exercise')
    # ### end Alembic commands ###
