"""Add is_archived to WorkoutPlan

Revision ID: ab50b9366d2e
Revises: 6bc0064384aa
Create Date: 2025-05-31 23:10:05.730338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab50b9366d2e'
down_revision = '6bc0064384aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
