"""Add current_workout_plan_id to User

Revision ID: f4d4e2d36206
Revises: 877472cd27b7
Create Date: 2025-05-29 11:59:17.256871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d4e2d36206'
down_revision = '877472cd27b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_workout_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_current_workout_plan_id',
            'workout_plan',
            ['current_workout_plan_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_workout_plan_id')

    # ### end Alembic commands ###
